name: MCP Todo .NET

networks:
  mcp-todo:
    name: mcp-todo

services:
  todo-server:
    container_name: todo-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3000:8080
    env_file:
      - path: ./.env
        required: true
    networks:
      - mcp-todo

  todo-client:
    container_name: todo-client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8080:8080
    depends_on:
      - todo-server
    env_file:
      - path: ./.env
        required: true
    environment:
      - McpServers__TodoList__Url=http://todo-server:8080
    networks:
      - mcp-todo
