# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/McpTodo.ServerApp /source/McpTodo.ServerApp
COPY ./src/McpTodo.ServiceDefaults /source/McpTodo.ServiceDefaults

WORKDIR /source/McpTodo.ServerApp

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "McpTodoList.ContainerApp.dll"]
